### ISSUE TITLE
Numbers have spaces when read contract

### ISSUE THREAD

**Issue by ericlee42** [blockscout/frontend#1692]
### Description

<img width="600" alt="image" src="https://github.com/blockscout/frontend/assets/92196970/fc221441-bd0e-4880-9fbd-ed53f2f459d7">

<img width="534" alt="image" src="https://github.com/blockscout/frontend/assets/92196970/6cfc2847-4415-438a-9c30-38a4809337ae">

I have tested it on local, the result is not correct, I think the bug it's related to the request data.

### Link to the page

https://explorer.holesky.metisdevops.link/address/0xdE8d56212118906a0CeCD331e842429714b4c47B?tab=read_proxy

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v1.26.0-alpha

### Operating system

None

**Comment by ericlee42** [comment]
I tried main branch, but the api returns an errror

```
{"time":"2024-03-13T23:23:12.378Z","severity":"error","message":"#PID<0.6005.0> running BlockScoutWeb.Endpoint (connection #PID<0.6004.0>, stream id 1) terminated\nServer: sepolia-explorer-api.metisdevops.link:80 (http)\nRequest: POST /api/v2/smart-contracts/0x32412F6452fe27b61cAbc09De3C9EDfDfc4B3Ab8/query-read-method?is_custom_abi=false\n** (exit) an exception was raised:\n ** (FunctionClauseError) no function clause matching in Integer.parse/2\n (elixir 1.14.5) lib/integer.ex:275: Integer.parse(1500, 10)\n (explorer 6.2.2) lib/explorer/smart_contract/reader.ex:683: Explorer.SmartContract.Reader.parse_item/1\n (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n (explorer 6.2.2) lib/explorer/smart_contract/reader.ex:570: Explorer.SmartContract.Reader.query_contract_and_link_outputs/7\n (explorer 6.2.2) lib/explorer/smart_contract/reader.ex:420: Explorer.SmartContract.Reader.query_function_with_names/7\n (block_scout_web 6.2.2) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:172: BlockScoutWeb.API.V2.SmartContractController.query_read_method/2\n (block_scout_web 6.2.2) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.action/2\n (block_scout_web 6.2.2) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.phoenix_controller_pipeline/2","metadata":{"error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in Integer.parse/2\n (elixir 1.14.5) lib/integer.ex:275: Integer.parse(1500, 10)\n (explorer 6.2.2) lib/explorer/smart_contract/reader.ex:683: Explorer.SmartContract.Reader.parse_item/1\n (elixir 1.14.5) lib/enum.ex:1658: Enum.\"-map/2-lists^map/1-0-\"/2\n (explorer 6.2.2) lib/explorer/smart_contract/reader.ex:570: Explorer.SmartContract.Reader.query_contract_and_link_outputs/7\n (explorer 6.2.2) lib/explorer/smart_contract/reader.ex:420: Explorer.SmartContract.Reader.query_function_with_names/7\n (block_scout_web 6.2.2) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:172: BlockScoutWeb.API.V2.SmartContractController.query_read_method/2\n (block_scout_web 6.2.2) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.action/2\n (block_scout_web 6.2.2) lib/block_scout_web/controllers/api/v2/smart_contract_controller.ex:1: BlockScoutWeb.API.V2.SmartContractController.phoenix_controller_pipeline/2\n"}}}
```

**Comment by ericlee42** [comment]
It's a number instead of string now

<img width="501" alt="image" src="https://github.com/blockscout/frontend/assets/92196970/05f2faa4-eb2c-4449-9dd9-d253f40198d8">

and it works with string

<img width="719" alt="image" src="https://github.com/blockscout/frontend/assets/92196970/d9dac8f3-2404-4a27-a674-7cd2c24d13a0">
