### ISSUE TITLE
broken docker release builds

### ISSUE THREAD

**Issue by InoMurko** [blockscout/frontend#2485]
### Description

```
ghcr.io/blockscout/frontend:v1.36.0
```
on a bedrock rollup:
<img width="574" alt="image" src="https://github.com/user-attachments/assets/0d010ab5-637d-411b-9848-bb7fa48e1eb8" />

Using build:
```
ghcr.io/blockscout/frontend:v1.37.0
```
page doesn't open. Backend works

### Link to the page

https://ino-1238.explorer.dev.caldera.xyz/

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

v.1.36

### Operating system

None

**Comment by InoMurko** [comment]
Actually release 1.36.4 works fine. Build 1.37 is broken.

**Comment by InoMurko** [comment]
1.37 logs
```

⬇️  Downloading external assets...
   [.] NEXT_PUBLIC_MARKETPLACE_CONFIG_URL: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_MARKETPLACE_CATEGORIES_URL: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_MARKETPLACE_SECURITY_REPORTS_URL: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_MARKETPLACE_BANNER_CONTENT_URL: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_MARKETPLACE_GRAPH_LINKS_URL: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_FEATURED_NETWORKS: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_FOOTER_LINKS: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_NETWORK_LOGO: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_NETWORK_LOGO_DARK: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_NETWORK_ICON: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_NETWORK_ICON_DARK: Variable is not set. Skipping download.
   [.] NEXT_PUBLIC_OG_IMAGE_URL: Variable is not set. Skipping download.
✅ Done.


🌀 Checking environment variables and their placeholders congruity...
👍 All good!

🌀 Checking deprecated environment variables...
👍 All good!

🌀 Validating ENV variables values...
👍 All good!

yarn install v1.22.22
warning ../../../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.12s.
Generating favicons...
Error in favicon generation process: Error: FAVICON_MASTER_URL or NEXT_PUBLIC_NETWORK_ICON must be set
    at generateFavicons (/app/deploy/tools/favicon-generator/index.js:13:13)
    at Object.<anonymous> (/app/deploy/tools/favicon-generator/index.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
👎 Unable to generate favicons bundle.

🌀 Creating client script with ENV values...
✅ Done.

📋 Here is the list of the features enabled for the running instance.
To adjust their configuration, please refer to the documentation - https://github.com/blockscout/frontend/blob/main/docs/ENVS.md#app-features

    [v] Advanced filter
    [ ] My account
    [ ] Address verification in "My account"
    [ ] Address metadata
    [ ] Banner ads
    [ ] Text ads
    [ ] Beacon chain
    [ ] Bridged tokens
    [v] Blockchain interaction (writing to contract, etc.)
    [ ] Celo chain
    [v] Export data to CSV file
    [ ] Data availability
    [ ] DeFi dropdown
    [ ] Easter egg badge
    [ ] Fault proof system
    [v] Gas tracker
    [ ] Get gas button
    [ ] Google analytics
    [v] GraphQL API documentation
    [ ] GrowthBook feature flagging and A/B testing
    [ ] Marketplace
    [ ] MetaSuites extension
    [ ] Mixpanel analytics
    [ ] MUD framework
    [ ] Multichain balance
    [ ] Name service integration
    [ ] DEX Pools
    [ ] Public tag submission
    [v] REST API documentation
    [ ] Rewards service integration
    [ ] Rollbar error monitoring
    [v] Rollup (L2) chain
    [ ] Safe address tags
    [ ] Save on gas with GasHawk
    [ ] Solidity to UML diagrams
    [v] Blockchain statistics
    [ ] SUAVE chain
    [ ] Transaction interpretation
    [ ] User operations
    [ ] User profile API
    [ ] Validators list
    [ ] Verified tokens info
    [v] Web3 wallet integration (add token or network to the wallet)
    [ ] XStar score

Starting Next.js application
   ▲ Next.js 15.0.3
   - Local:        http://frontend-75db994955-qsrzj:3000
   - Network:      http://10.0.216.172:3000

 ✓ Starting...
 ✓ Ready in 320ms
(node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by InoMurko** [comment]
Upon my inspection 1.36.4 works fine (but doesn't work with blockscout 6.10).
Upon my inspection 1.37 does not work (Bad gateway, 502).

**Comment by InoMurko** [comment]
For others searching... if you're letting traffic through ingress you have to bump "nginx.ingress.kubernetes.io/proxy-buffer-size": "128k" to at least 8k.
